language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  
install:
  - pip install pillow
  - pip install flake8
  - pip install pytest>=3.0

script:
  - flake8
  - py.test
